
CREATE DATABASE IF NOT EXISTS Galeria;
USE Galeria;
CREATE TABLE IF NOT EXISTS POST (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Titulo VARCHAR(255) NOT NULL,
    Path_Imagem VARCHAR(255) NOT NULL,
    Descricao TEXT
);